// Embeds skills/*/SKILL.md into src/mcp/skills.generated.ts so the single-file
// dist bundle and compiled exe can serve them as MCP resources (tracks draft SEP-2640).
// Frontmatter constraints: single-line `name:` and `description:` values.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface EmbeddedSkill {
  name: string;
  description: string;
  uri: string;
  mimeType: string;
  text: string;
}

const NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

export async function collectSkills(skillsDir: string): Promise<EmbeddedSkill[]> {
  const out: EmbeddedSkill[] = [];
  for (const entry of await readdir(skillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const raw = await readFile(join(skillsDir, entry.name, "SKILL.md"), "utf8");
    const text = raw.replace(/\r\n/g, "\n");
    const fm = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
    if (!fm) throw new Error(`${entry.name}/SKILL.md: missing YAML frontmatter`);
    const name = /^name:\s*(.+)\s*$/m.exec(fm[1]!)?.[1]?.trim();
    const description = /^description:\s*(.+)\s*$/m.exec(fm[1]!)?.[1]?.trim();
    if (!name || name !== entry.name) throw new Error(`${entry.name}/SKILL.md: frontmatter name must equal directory name`);
    if (!NAME_RE.test(name)) throw new Error(`${name}: skill names use lowercase letters, digits, hyphens`);
    if (!description) throw new Error(`${name}: frontmatter description is required`);
    out.push({ name, description, uri: `skill://${name}/SKILL.md`, mimeType: "text/markdown", text });
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  if (out.length === 0) throw new Error(`no skills found under ${skillsDir}`);
  return out;
}

export function renderModule(skills: EmbeddedSkill[]): string {
  const index = {
    $schema: "https://schemas.agentskills.io/discovery/0.2.0/schema.json",
    skills: skills.map((s) => ({ name: s.name, type: "skill-md", description: s.description, url: s.uri })),
  };
  return (
    "// GENERATED by scripts/embed-skills.ts — do not edit.\n" +
    "// Edit skills/*/SKILL.md and run: bun run embed-skills\n" +
    "export interface EmbeddedSkill {\n  name: string;\n  description: string;\n  uri: string;\n  mimeType: string;\n  text: string;\n}\n\n" +
    `export const skills: EmbeddedSkill[] = ${JSON.stringify(skills, null, 2)};\n\n` +
    `export const skillsIndexJson: string = ${JSON.stringify(JSON.stringify(index, null, 2))};\n`
  );
}

if (import.meta.main) {
  const repoRoot = join(import.meta.dir, "..");
  const skills = await collectSkills(join(repoRoot, "skills"));
  await writeFile(join(repoRoot, "src", "mcp", "skills.generated.ts"), renderModule(skills));
  console.log(`embedded ${skills.length} skills -> src/mcp/skills.generated.ts`);
}
